# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ShadowKill_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shadowkill(object):
    def setupUi(self, shadowkill):
        shadowkill.setObjectName("shadowkill")
        shadowkill.resize(1101, 808)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(shadowkill)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(300, 680, 781, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.game_player_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.game_player_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.game_player_horizontalLayout.setObjectName("game_player_horizontalLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(shadowkill)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 271, 741))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_3.setMouseTracking(False)
        self.lineEdit_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.unlock_pushbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.unlock_pushbutton.setObjectName("unlock_pushbutton")
        self.verticalLayout.addWidget(self.unlock_pushbutton)
        self.sure_name_pushbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.sure_name_pushbutton.setObjectName("sure_name_pushbutton")
        self.verticalLayout.addWidget(self.sure_name_pushbutton)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.name_textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.name_textEdit.setObjectName("name_textEdit")
        self.verticalLayout.addWidget(self.name_textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.theme_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.theme_comboBox.setObjectName("theme_comboBox")
        self.verticalLayout_2.addWidget(self.theme_comboBox)
        self.load_config_pushbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load_config_pushbutton.setObjectName("load_config_pushbutton")
        self.verticalLayout_2.addWidget(self.load_config_pushbutton)
        self.load_name_pushbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load_name_pushbutton.setObjectName("load_name_pushbutton")
        self.verticalLayout_2.addWidget(self.load_name_pushbutton)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_2.setMouseTracking(False)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.operation_history_textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.operation_history_textEdit.setMouseTracking(False)
        self.operation_history_textEdit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.operation_history_textEdit.setObjectName("operation_history_textEdit")
        self.verticalLayout_2.addWidget(self.operation_history_textEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(shadowkill)
        QtCore.QMetaObject.connectSlotsByName(shadowkill)

    def retranslateUi(self, shadowkill):
        _translate = QtCore.QCoreApplication.translate
        shadowkill.setWindowTitle(_translate("shadowkill", "Form"))
        self.lineEdit_3.setText(_translate("shadowkill", "主题选择"))
        self.unlock_pushbutton.setText(_translate("shadowkill", "解除锁定"))
        self.sure_name_pushbutton.setText(_translate("shadowkill", "确定"))
        self.lineEdit.setText(_translate("shadowkill", "参与者名单"))
        self.load_config_pushbutton.setText(_translate("shadowkill", "读取配置文件"))
        self.load_name_pushbutton.setText(_translate("shadowkill", "读取名字文件"))
        self.lineEdit_2.setText(_translate("shadowkill", "操作历史"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    shadowkill = QtWidgets.QWidget()
    ui = Ui_shadowkill()
    ui.setupUi(shadowkill)
    shadowkill.show()
    sys.exit(app.exec_())
